terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

provider "cloudflare" {
  # email   = var.cloudflare_email   # CLOUDFLARE_EMAIL
  # api_key = var.cloudflare_api_key # CLOUDFLARE_API_KEY
}

data "cloudflare_zone" "domain" {
  name = var.domain
}

resource "cloudflare_record" "apex_a_records" {
  count   = length(var.gh_pages_ipv6)
  zone_id = data.cloudflare_zone.domain.id
  name    = "@"
  type    = "A"
  value   = var.gh_pages_ipv4[count.index]
  ttl     = 300
  proxied = false

}

resource "cloudflare_record" "apex_aaaa" {
  count   = length(var.gh_pages_ipv6)
  zone_id = data.cloudflare_zone.domain.id
  name    = "@"
  type    = "AAAA"
  value   = var.gh_pages_ipv6[count.index]
  ttl     = 300
  proxied = false
}

resource "cloudflare_record" "cnames" {
  for_each = var.gh_pages_cnames
  zone_id  = data.cloudflare_zone.domain.id
  name     = each.value
  type     = "CNAME"
  value    = "${var.gh_username}.github.io"
  ttl      = 300
  proxied  = false
}

resource "cloudflare_record" "api" {
  zone_id = data.cloudflare_zone.domain.id
  name    = "api"
  type    = "CNAME"
  value   = var.heroku_api_cname
  proxied = true
}

# These records are generated by Cloudflare. They can be removed by disabling
# Email Routing on the domain.

# resource "cloudflare_record" "mx1" {
#   zone_id  = data.cloudflare_zone.domain.id
#   name     = "@"
#   type     = "MX"
#   value    = "route1.mx.cloudflare.net"
#   priority = 83
# }

# resource "cloudflare_record" "mx2" {
#   zone_id  = data.cloudflare_zone.domain.id
#   name     = "@"
#   type     = "MX"
#   value    = "route2.mx.cloudflare.net"
#   priority = 34
# }

# resource "cloudflare_record" "mx3" {
#   zone_id  = data.cloudflare_zone.domain.id
#   name     = "@"
#   type     = "MX"
#   value    = "route3.mx.cloudflare.net"
#   priority = 52
# }

resource "cloudflare_record" "spf" {
  zone_id = data.cloudflare_zone.domain.id
  name    = "@"
  type    = "TXT"
  value   = "v=spf1 include:_spf.mx.cloudflare.net ~all"
}

resource "cloudflare_record" "dmarc" {
  zone_id = data.cloudflare_zone.domain.id
  name    = "_dmarc"
  type    = "TXT"
  value   = "v=DMARC1; p=none; rua=mailto:syntaqx@gmail.com"
}
